server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: message-service
              uri: lb://MESSAGE-SERVICE
              predicates:
                - Path=/api/users/*/mentor_sessions/**

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**

            - id: user-service-student
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/student/**

            - id: file-service
              uri: lb://FILE-SERVICE
              predicates:
                - Path=/api/file/**

            - id: exam-service
              uri: lb://EXAM-SERVICE
              predicates:
                - Path=/api/exam/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
