spring:
  application:
    name: user-service
  config:
    import: optional:configserver:https://config-server-53266248406.europe-west1.run.app

server:
  port: ${PORT:8085}

firebase:
  service-account-key-path: ${FIREBASE_SERVICE_ACCOUNT_JSON}
  storage-bucket: career-compass-e2f8b.appspot.com