firebase:
  service-account-key-path: ${FIREBASE_SERVICE_ACCOUNT_JSON}
  storage-bucket: career-compass-e2f8b.appspot.com

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#    instance-id: ${spring.application.name}:${server.port}